// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Screend.Data;

namespace Screend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190313213651_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Screend.Entities.Movie.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Age");

                    b.Property<string>("Description");

                    b.Property<string>("Genre");

                    b.Property<string>("Img");

                    b.Property<string>("Language");

                    b.Property<string>("Rating");

                    b.Property<int>("Runtime");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Screend.Entities.Movie.MovieTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.ToTable("MovieTickets");
                });

            modelBuilder.Entity("Screend.Entities.Order.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MollieId");

                    b.Property<int>("Paid");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Screend.Entities.Order.OrderArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ArticleId");

                    b.Property<int>("OrderId");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderArticles");
                });

            modelBuilder.Entity("Screend.Entities.Order.OrderChair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ChairId");

                    b.Property<int?>("MovieTicketId");

                    b.Property<int>("OrderId");

                    b.Property<int>("ScheduleId");

                    b.Property<int?>("TheaterChairId");

                    b.Property<int>("TicketId");

                    b.HasKey("Id");

                    b.HasIndex("MovieTicketId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("TheaterChairId");

                    b.ToTable("OrderChairs");
                });

            modelBuilder.Entity("Screend.Entities.Schedule.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MovieId");

                    b.Property<int>("TheaterId");

                    b.Property<DateTime>("Time");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("TheaterId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Screend.Entities.Theater.Theater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Has3D");

                    b.Property<string>("Name");

                    b.Property<bool>("WheelchairAccessible");

                    b.HasKey("Id");

                    b.ToTable("Theaters");

                    b.HasData(
                        new { Id = 1, Has3D = true, Name = "Zaal 1", WheelchairAccessible = true },
                        new { Id = 2, Has3D = true, Name = "Zaal 2", WheelchairAccessible = true },
                        new { Id = 3, Has3D = false, Name = "Zaal 3", WheelchairAccessible = true },
                        new { Id = 4, Has3D = false, Name = "Zaal 4", WheelchairAccessible = true },
                        new { Id = 5, Has3D = false, Name = "Zaal 5", WheelchairAccessible = false },
                        new { Id = 6, Has3D = false, Name = "Zaal 6", WheelchairAccessible = false }
                    );
                });

            modelBuilder.Entity("Screend.Entities.Theater.TheaterArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.ToTable("TheaterArticles");
                });

            modelBuilder.Entity("Screend.Entities.Theater.TheaterChair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ChairNumber");

                    b.Property<int>("TheaterRowId");

                    b.HasKey("Id");

                    b.HasIndex("TheaterRowId");

                    b.ToTable("TheaterChairs");

                    b.HasData(
                        new { Id = 1, ChairNumber = 1, TheaterRowId = 1 },
                        new { Id = 2, ChairNumber = 2, TheaterRowId = 1 },
                        new { Id = 3, ChairNumber = 3, TheaterRowId = 1 },
                        new { Id = 4, ChairNumber = 4, TheaterRowId = 1 },
                        new { Id = 5, ChairNumber = 5, TheaterRowId = 1 },
                        new { Id = 6, ChairNumber = 6, TheaterRowId = 1 },
                        new { Id = 7, ChairNumber = 7, TheaterRowId = 1 },
                        new { Id = 8, ChairNumber = 8, TheaterRowId = 1 },
                        new { Id = 9, ChairNumber = 9, TheaterRowId = 1 },
                        new { Id = 10, ChairNumber = 10, TheaterRowId = 1 },
                        new { Id = 11, ChairNumber = 11, TheaterRowId = 1 },
                        new { Id = 12, ChairNumber = 12, TheaterRowId = 1 },
                        new { Id = 13, ChairNumber = 13, TheaterRowId = 1 },
                        new { Id = 14, ChairNumber = 14, TheaterRowId = 1 },
                        new { Id = 15, ChairNumber = 15, TheaterRowId = 1 },
                        new { Id = 16, ChairNumber = 1, TheaterRowId = 2 },
                        new { Id = 17, ChairNumber = 2, TheaterRowId = 2 },
                        new { Id = 18, ChairNumber = 3, TheaterRowId = 2 },
                        new { Id = 19, ChairNumber = 4, TheaterRowId = 2 },
                        new { Id = 20, ChairNumber = 5, TheaterRowId = 2 },
                        new { Id = 21, ChairNumber = 6, TheaterRowId = 2 },
                        new { Id = 22, ChairNumber = 7, TheaterRowId = 2 },
                        new { Id = 23, ChairNumber = 8, TheaterRowId = 2 },
                        new { Id = 24, ChairNumber = 9, TheaterRowId = 2 },
                        new { Id = 25, ChairNumber = 10, TheaterRowId = 2 },
                        new { Id = 26, ChairNumber = 11, TheaterRowId = 2 },
                        new { Id = 27, ChairNumber = 12, TheaterRowId = 2 },
                        new { Id = 28, ChairNumber = 13, TheaterRowId = 2 },
                        new { Id = 29, ChairNumber = 14, TheaterRowId = 2 },
                        new { Id = 30, ChairNumber = 15, TheaterRowId = 2 },
                        new { Id = 31, ChairNumber = 1, TheaterRowId = 3 },
                        new { Id = 32, ChairNumber = 2, TheaterRowId = 3 },
                        new { Id = 33, ChairNumber = 3, TheaterRowId = 3 },
                        new { Id = 34, ChairNumber = 4, TheaterRowId = 3 },
                        new { Id = 35, ChairNumber = 5, TheaterRowId = 3 },
                        new { Id = 36, ChairNumber = 6, TheaterRowId = 3 },
                        new { Id = 37, ChairNumber = 7, TheaterRowId = 3 },
                        new { Id = 38, ChairNumber = 8, TheaterRowId = 3 },
                        new { Id = 39, ChairNumber = 9, TheaterRowId = 3 },
                        new { Id = 40, ChairNumber = 10, TheaterRowId = 3 },
                        new { Id = 41, ChairNumber = 11, TheaterRowId = 3 },
                        new { Id = 42, ChairNumber = 12, TheaterRowId = 3 },
                        new { Id = 43, ChairNumber = 13, TheaterRowId = 3 },
                        new { Id = 44, ChairNumber = 14, TheaterRowId = 3 },
                        new { Id = 45, ChairNumber = 15, TheaterRowId = 3 },
                        new { Id = 46, ChairNumber = 1, TheaterRowId = 4 },
                        new { Id = 47, ChairNumber = 2, TheaterRowId = 4 },
                        new { Id = 48, ChairNumber = 3, TheaterRowId = 4 },
                        new { Id = 49, ChairNumber = 4, TheaterRowId = 4 },
                        new { Id = 50, ChairNumber = 5, TheaterRowId = 4 },
                        new { Id = 51, ChairNumber = 6, TheaterRowId = 4 },
                        new { Id = 52, ChairNumber = 7, TheaterRowId = 4 },
                        new { Id = 53, ChairNumber = 8, TheaterRowId = 4 },
                        new { Id = 54, ChairNumber = 9, TheaterRowId = 4 },
                        new { Id = 55, ChairNumber = 10, TheaterRowId = 4 },
                        new { Id = 56, ChairNumber = 11, TheaterRowId = 4 },
                        new { Id = 57, ChairNumber = 12, TheaterRowId = 4 },
                        new { Id = 58, ChairNumber = 13, TheaterRowId = 4 },
                        new { Id = 59, ChairNumber = 14, TheaterRowId = 4 },
                        new { Id = 60, ChairNumber = 15, TheaterRowId = 4 },
                        new { Id = 61, ChairNumber = 1, TheaterRowId = 5 },
                        new { Id = 62, ChairNumber = 2, TheaterRowId = 5 },
                        new { Id = 63, ChairNumber = 3, TheaterRowId = 5 },
                        new { Id = 64, ChairNumber = 4, TheaterRowId = 5 },
                        new { Id = 65, ChairNumber = 5, TheaterRowId = 5 },
                        new { Id = 66, ChairNumber = 6, TheaterRowId = 5 },
                        new { Id = 67, ChairNumber = 7, TheaterRowId = 5 },
                        new { Id = 68, ChairNumber = 8, TheaterRowId = 5 },
                        new { Id = 69, ChairNumber = 9, TheaterRowId = 5 },
                        new { Id = 70, ChairNumber = 10, TheaterRowId = 5 },
                        new { Id = 71, ChairNumber = 11, TheaterRowId = 5 },
                        new { Id = 72, ChairNumber = 12, TheaterRowId = 5 },
                        new { Id = 73, ChairNumber = 13, TheaterRowId = 5 },
                        new { Id = 74, ChairNumber = 14, TheaterRowId = 5 },
                        new { Id = 75, ChairNumber = 15, TheaterRowId = 5 },
                        new { Id = 76, ChairNumber = 1, TheaterRowId = 6 },
                        new { Id = 77, ChairNumber = 2, TheaterRowId = 6 },
                        new { Id = 78, ChairNumber = 3, TheaterRowId = 6 },
                        new { Id = 79, ChairNumber = 4, TheaterRowId = 6 },
                        new { Id = 80, ChairNumber = 5, TheaterRowId = 6 },
                        new { Id = 81, ChairNumber = 6, TheaterRowId = 6 },
                        new { Id = 82, ChairNumber = 7, TheaterRowId = 6 },
                        new { Id = 83, ChairNumber = 8, TheaterRowId = 6 },
                        new { Id = 84, ChairNumber = 9, TheaterRowId = 6 },
                        new { Id = 85, ChairNumber = 10, TheaterRowId = 6 },
                        new { Id = 86, ChairNumber = 11, TheaterRowId = 6 },
                        new { Id = 87, ChairNumber = 12, TheaterRowId = 6 },
                        new { Id = 88, ChairNumber = 13, TheaterRowId = 6 },
                        new { Id = 89, ChairNumber = 14, TheaterRowId = 6 },
                        new { Id = 90, ChairNumber = 15, TheaterRowId = 6 },
                        new { Id = 91, ChairNumber = 1, TheaterRowId = 7 },
                        new { Id = 92, ChairNumber = 2, TheaterRowId = 7 },
                        new { Id = 93, ChairNumber = 3, TheaterRowId = 7 },
                        new { Id = 94, ChairNumber = 4, TheaterRowId = 7 },
                        new { Id = 95, ChairNumber = 5, TheaterRowId = 7 },
                        new { Id = 96, ChairNumber = 6, TheaterRowId = 7 },
                        new { Id = 97, ChairNumber = 7, TheaterRowId = 7 },
                        new { Id = 98, ChairNumber = 8, TheaterRowId = 7 },
                        new { Id = 99, ChairNumber = 9, TheaterRowId = 7 },
                        new { Id = 100, ChairNumber = 10, TheaterRowId = 7 },
                        new { Id = 101, ChairNumber = 11, TheaterRowId = 7 },
                        new { Id = 102, ChairNumber = 12, TheaterRowId = 7 },
                        new { Id = 103, ChairNumber = 13, TheaterRowId = 7 },
                        new { Id = 104, ChairNumber = 14, TheaterRowId = 7 },
                        new { Id = 105, ChairNumber = 15, TheaterRowId = 7 },
                        new { Id = 106, ChairNumber = 1, TheaterRowId = 8 },
                        new { Id = 107, ChairNumber = 2, TheaterRowId = 8 },
                        new { Id = 108, ChairNumber = 3, TheaterRowId = 8 },
                        new { Id = 109, ChairNumber = 4, TheaterRowId = 8 },
                        new { Id = 110, ChairNumber = 5, TheaterRowId = 8 },
                        new { Id = 111, ChairNumber = 6, TheaterRowId = 8 },
                        new { Id = 112, ChairNumber = 7, TheaterRowId = 8 },
                        new { Id = 113, ChairNumber = 8, TheaterRowId = 8 },
                        new { Id = 114, ChairNumber = 9, TheaterRowId = 8 },
                        new { Id = 115, ChairNumber = 10, TheaterRowId = 8 },
                        new { Id = 116, ChairNumber = 11, TheaterRowId = 8 },
                        new { Id = 117, ChairNumber = 12, TheaterRowId = 8 },
                        new { Id = 118, ChairNumber = 13, TheaterRowId = 8 },
                        new { Id = 119, ChairNumber = 14, TheaterRowId = 8 },
                        new { Id = 120, ChairNumber = 15, TheaterRowId = 8 },
                        new { Id = 121, ChairNumber = 1, TheaterRowId = 9 },
                        new { Id = 122, ChairNumber = 2, TheaterRowId = 9 },
                        new { Id = 123, ChairNumber = 3, TheaterRowId = 9 },
                        new { Id = 124, ChairNumber = 4, TheaterRowId = 9 },
                        new { Id = 125, ChairNumber = 5, TheaterRowId = 9 },
                        new { Id = 126, ChairNumber = 6, TheaterRowId = 9 },
                        new { Id = 127, ChairNumber = 7, TheaterRowId = 9 },
                        new { Id = 128, ChairNumber = 8, TheaterRowId = 9 },
                        new { Id = 129, ChairNumber = 9, TheaterRowId = 9 },
                        new { Id = 130, ChairNumber = 10, TheaterRowId = 9 },
                        new { Id = 131, ChairNumber = 11, TheaterRowId = 9 },
                        new { Id = 132, ChairNumber = 12, TheaterRowId = 9 },
                        new { Id = 133, ChairNumber = 13, TheaterRowId = 9 },
                        new { Id = 134, ChairNumber = 14, TheaterRowId = 9 },
                        new { Id = 135, ChairNumber = 15, TheaterRowId = 9 },
                        new { Id = 136, ChairNumber = 1, TheaterRowId = 10 },
                        new { Id = 137, ChairNumber = 2, TheaterRowId = 10 },
                        new { Id = 138, ChairNumber = 3, TheaterRowId = 10 },
                        new { Id = 139, ChairNumber = 4, TheaterRowId = 10 },
                        new { Id = 140, ChairNumber = 5, TheaterRowId = 10 },
                        new { Id = 141, ChairNumber = 6, TheaterRowId = 10 },
                        new { Id = 142, ChairNumber = 7, TheaterRowId = 10 },
                        new { Id = 143, ChairNumber = 8, TheaterRowId = 10 },
                        new { Id = 144, ChairNumber = 9, TheaterRowId = 10 },
                        new { Id = 145, ChairNumber = 10, TheaterRowId = 10 },
                        new { Id = 146, ChairNumber = 11, TheaterRowId = 10 },
                        new { Id = 147, ChairNumber = 12, TheaterRowId = 10 },
                        new { Id = 148, ChairNumber = 13, TheaterRowId = 10 },
                        new { Id = 149, ChairNumber = 14, TheaterRowId = 10 },
                        new { Id = 150, ChairNumber = 15, TheaterRowId = 10 },
                        new { Id = 151, ChairNumber = 1, TheaterRowId = 11 },
                        new { Id = 152, ChairNumber = 2, TheaterRowId = 11 },
                        new { Id = 153, ChairNumber = 3, TheaterRowId = 11 },
                        new { Id = 154, ChairNumber = 4, TheaterRowId = 11 },
                        new { Id = 155, ChairNumber = 5, TheaterRowId = 11 },
                        new { Id = 156, ChairNumber = 6, TheaterRowId = 11 },
                        new { Id = 157, ChairNumber = 7, TheaterRowId = 11 },
                        new { Id = 158, ChairNumber = 8, TheaterRowId = 11 },
                        new { Id = 159, ChairNumber = 9, TheaterRowId = 11 },
                        new { Id = 160, ChairNumber = 10, TheaterRowId = 11 },
                        new { Id = 161, ChairNumber = 11, TheaterRowId = 11 },
                        new { Id = 162, ChairNumber = 12, TheaterRowId = 11 },
                        new { Id = 163, ChairNumber = 13, TheaterRowId = 11 },
                        new { Id = 164, ChairNumber = 14, TheaterRowId = 11 },
                        new { Id = 165, ChairNumber = 15, TheaterRowId = 11 },
                        new { Id = 166, ChairNumber = 1, TheaterRowId = 12 },
                        new { Id = 167, ChairNumber = 2, TheaterRowId = 12 },
                        new { Id = 168, ChairNumber = 3, TheaterRowId = 12 },
                        new { Id = 169, ChairNumber = 4, TheaterRowId = 12 },
                        new { Id = 170, ChairNumber = 5, TheaterRowId = 12 },
                        new { Id = 171, ChairNumber = 6, TheaterRowId = 12 },
                        new { Id = 172, ChairNumber = 7, TheaterRowId = 12 },
                        new { Id = 173, ChairNumber = 8, TheaterRowId = 12 },
                        new { Id = 174, ChairNumber = 9, TheaterRowId = 12 },
                        new { Id = 175, ChairNumber = 10, TheaterRowId = 12 },
                        new { Id = 176, ChairNumber = 11, TheaterRowId = 12 },
                        new { Id = 177, ChairNumber = 12, TheaterRowId = 12 },
                        new { Id = 178, ChairNumber = 13, TheaterRowId = 12 },
                        new { Id = 179, ChairNumber = 14, TheaterRowId = 12 },
                        new { Id = 180, ChairNumber = 15, TheaterRowId = 12 },
                        new { Id = 181, ChairNumber = 1, TheaterRowId = 13 },
                        new { Id = 182, ChairNumber = 2, TheaterRowId = 13 },
                        new { Id = 183, ChairNumber = 3, TheaterRowId = 13 },
                        new { Id = 184, ChairNumber = 4, TheaterRowId = 13 },
                        new { Id = 185, ChairNumber = 5, TheaterRowId = 13 },
                        new { Id = 186, ChairNumber = 6, TheaterRowId = 13 },
                        new { Id = 187, ChairNumber = 7, TheaterRowId = 13 },
                        new { Id = 188, ChairNumber = 8, TheaterRowId = 13 },
                        new { Id = 189, ChairNumber = 9, TheaterRowId = 13 },
                        new { Id = 190, ChairNumber = 10, TheaterRowId = 13 },
                        new { Id = 191, ChairNumber = 11, TheaterRowId = 13 },
                        new { Id = 192, ChairNumber = 12, TheaterRowId = 13 },
                        new { Id = 193, ChairNumber = 13, TheaterRowId = 13 },
                        new { Id = 194, ChairNumber = 14, TheaterRowId = 13 },
                        new { Id = 195, ChairNumber = 15, TheaterRowId = 13 },
                        new { Id = 196, ChairNumber = 1, TheaterRowId = 14 },
                        new { Id = 197, ChairNumber = 2, TheaterRowId = 14 },
                        new { Id = 198, ChairNumber = 3, TheaterRowId = 14 },
                        new { Id = 199, ChairNumber = 4, TheaterRowId = 14 },
                        new { Id = 200, ChairNumber = 5, TheaterRowId = 14 },
                        new { Id = 201, ChairNumber = 6, TheaterRowId = 14 },
                        new { Id = 202, ChairNumber = 7, TheaterRowId = 14 },
                        new { Id = 203, ChairNumber = 8, TheaterRowId = 14 },
                        new { Id = 204, ChairNumber = 9, TheaterRowId = 14 },
                        new { Id = 205, ChairNumber = 10, TheaterRowId = 14 },
                        new { Id = 206, ChairNumber = 11, TheaterRowId = 14 },
                        new { Id = 207, ChairNumber = 12, TheaterRowId = 14 },
                        new { Id = 208, ChairNumber = 13, TheaterRowId = 14 },
                        new { Id = 209, ChairNumber = 14, TheaterRowId = 14 },
                        new { Id = 210, ChairNumber = 15, TheaterRowId = 14 },
                        new { Id = 211, ChairNumber = 1, TheaterRowId = 15 },
                        new { Id = 212, ChairNumber = 2, TheaterRowId = 15 },
                        new { Id = 213, ChairNumber = 3, TheaterRowId = 15 },
                        new { Id = 214, ChairNumber = 4, TheaterRowId = 15 },
                        new { Id = 215, ChairNumber = 5, TheaterRowId = 15 },
                        new { Id = 216, ChairNumber = 6, TheaterRowId = 15 },
                        new { Id = 217, ChairNumber = 7, TheaterRowId = 15 },
                        new { Id = 218, ChairNumber = 8, TheaterRowId = 15 },
                        new { Id = 219, ChairNumber = 9, TheaterRowId = 15 },
                        new { Id = 220, ChairNumber = 10, TheaterRowId = 15 },
                        new { Id = 221, ChairNumber = 11, TheaterRowId = 15 },
                        new { Id = 222, ChairNumber = 12, TheaterRowId = 15 },
                        new { Id = 223, ChairNumber = 13, TheaterRowId = 15 },
                        new { Id = 224, ChairNumber = 14, TheaterRowId = 15 },
                        new { Id = 225, ChairNumber = 15, TheaterRowId = 15 },
                        new { Id = 226, ChairNumber = 1, TheaterRowId = 16 },
                        new { Id = 227, ChairNumber = 2, TheaterRowId = 16 },
                        new { Id = 228, ChairNumber = 3, TheaterRowId = 16 },
                        new { Id = 229, ChairNumber = 4, TheaterRowId = 16 },
                        new { Id = 230, ChairNumber = 5, TheaterRowId = 16 },
                        new { Id = 231, ChairNumber = 6, TheaterRowId = 16 },
                        new { Id = 232, ChairNumber = 7, TheaterRowId = 16 },
                        new { Id = 233, ChairNumber = 8, TheaterRowId = 16 },
                        new { Id = 234, ChairNumber = 9, TheaterRowId = 16 },
                        new { Id = 235, ChairNumber = 10, TheaterRowId = 16 },
                        new { Id = 236, ChairNumber = 11, TheaterRowId = 16 },
                        new { Id = 237, ChairNumber = 12, TheaterRowId = 16 },
                        new { Id = 238, ChairNumber = 13, TheaterRowId = 16 },
                        new { Id = 239, ChairNumber = 14, TheaterRowId = 16 },
                        new { Id = 240, ChairNumber = 15, TheaterRowId = 16 },
                        new { Id = 241, ChairNumber = 1, TheaterRowId = 17 },
                        new { Id = 242, ChairNumber = 2, TheaterRowId = 17 },
                        new { Id = 243, ChairNumber = 3, TheaterRowId = 17 },
                        new { Id = 244, ChairNumber = 4, TheaterRowId = 17 },
                        new { Id = 245, ChairNumber = 5, TheaterRowId = 17 },
                        new { Id = 246, ChairNumber = 6, TheaterRowId = 17 },
                        new { Id = 247, ChairNumber = 7, TheaterRowId = 17 },
                        new { Id = 248, ChairNumber = 8, TheaterRowId = 17 },
                        new { Id = 249, ChairNumber = 9, TheaterRowId = 17 },
                        new { Id = 250, ChairNumber = 10, TheaterRowId = 17 },
                        new { Id = 251, ChairNumber = 11, TheaterRowId = 17 },
                        new { Id = 252, ChairNumber = 12, TheaterRowId = 17 },
                        new { Id = 253, ChairNumber = 13, TheaterRowId = 17 },
                        new { Id = 254, ChairNumber = 14, TheaterRowId = 17 },
                        new { Id = 255, ChairNumber = 15, TheaterRowId = 17 },
                        new { Id = 256, ChairNumber = 1, TheaterRowId = 18 },
                        new { Id = 257, ChairNumber = 2, TheaterRowId = 18 },
                        new { Id = 258, ChairNumber = 3, TheaterRowId = 18 },
                        new { Id = 259, ChairNumber = 4, TheaterRowId = 18 },
                        new { Id = 260, ChairNumber = 5, TheaterRowId = 18 },
                        new { Id = 261, ChairNumber = 6, TheaterRowId = 18 },
                        new { Id = 262, ChairNumber = 7, TheaterRowId = 18 },
                        new { Id = 263, ChairNumber = 8, TheaterRowId = 18 },
                        new { Id = 264, ChairNumber = 9, TheaterRowId = 18 },
                        new { Id = 265, ChairNumber = 10, TheaterRowId = 18 },
                        new { Id = 266, ChairNumber = 11, TheaterRowId = 18 },
                        new { Id = 267, ChairNumber = 12, TheaterRowId = 18 },
                        new { Id = 268, ChairNumber = 13, TheaterRowId = 18 },
                        new { Id = 269, ChairNumber = 14, TheaterRowId = 18 },
                        new { Id = 270, ChairNumber = 15, TheaterRowId = 18 },
                        new { Id = 271, ChairNumber = 1, TheaterRowId = 19 },
                        new { Id = 272, ChairNumber = 2, TheaterRowId = 19 },
                        new { Id = 273, ChairNumber = 3, TheaterRowId = 19 },
                        new { Id = 274, ChairNumber = 4, TheaterRowId = 19 },
                        new { Id = 275, ChairNumber = 5, TheaterRowId = 19 },
                        new { Id = 276, ChairNumber = 6, TheaterRowId = 19 },
                        new { Id = 277, ChairNumber = 7, TheaterRowId = 19 },
                        new { Id = 278, ChairNumber = 8, TheaterRowId = 19 },
                        new { Id = 279, ChairNumber = 9, TheaterRowId = 19 },
                        new { Id = 280, ChairNumber = 10, TheaterRowId = 19 },
                        new { Id = 281, ChairNumber = 11, TheaterRowId = 19 },
                        new { Id = 282, ChairNumber = 12, TheaterRowId = 19 },
                        new { Id = 283, ChairNumber = 13, TheaterRowId = 19 },
                        new { Id = 284, ChairNumber = 14, TheaterRowId = 19 },
                        new { Id = 285, ChairNumber = 15, TheaterRowId = 19 },
                        new { Id = 286, ChairNumber = 1, TheaterRowId = 20 },
                        new { Id = 287, ChairNumber = 2, TheaterRowId = 20 },
                        new { Id = 288, ChairNumber = 3, TheaterRowId = 20 },
                        new { Id = 289, ChairNumber = 4, TheaterRowId = 20 },
                        new { Id = 290, ChairNumber = 5, TheaterRowId = 20 },
                        new { Id = 291, ChairNumber = 6, TheaterRowId = 20 },
                        new { Id = 292, ChairNumber = 7, TheaterRowId = 20 },
                        new { Id = 293, ChairNumber = 8, TheaterRowId = 20 },
                        new { Id = 294, ChairNumber = 9, TheaterRowId = 20 },
                        new { Id = 295, ChairNumber = 10, TheaterRowId = 20 },
                        new { Id = 296, ChairNumber = 11, TheaterRowId = 20 },
                        new { Id = 297, ChairNumber = 12, TheaterRowId = 20 },
                        new { Id = 298, ChairNumber = 13, TheaterRowId = 20 },
                        new { Id = 299, ChairNumber = 14, TheaterRowId = 20 },
                        new { Id = 300, ChairNumber = 15, TheaterRowId = 20 },
                        new { Id = 301, ChairNumber = 1, TheaterRowId = 21 },
                        new { Id = 302, ChairNumber = 2, TheaterRowId = 21 },
                        new { Id = 303, ChairNumber = 3, TheaterRowId = 21 },
                        new { Id = 304, ChairNumber = 4, TheaterRowId = 21 },
                        new { Id = 305, ChairNumber = 5, TheaterRowId = 21 },
                        new { Id = 306, ChairNumber = 6, TheaterRowId = 21 },
                        new { Id = 307, ChairNumber = 7, TheaterRowId = 21 },
                        new { Id = 308, ChairNumber = 8, TheaterRowId = 21 },
                        new { Id = 309, ChairNumber = 9, TheaterRowId = 21 },
                        new { Id = 310, ChairNumber = 10, TheaterRowId = 21 },
                        new { Id = 311, ChairNumber = 11, TheaterRowId = 21 },
                        new { Id = 312, ChairNumber = 12, TheaterRowId = 21 },
                        new { Id = 313, ChairNumber = 13, TheaterRowId = 21 },
                        new { Id = 314, ChairNumber = 14, TheaterRowId = 21 },
                        new { Id = 315, ChairNumber = 15, TheaterRowId = 21 },
                        new { Id = 316, ChairNumber = 1, TheaterRowId = 22 },
                        new { Id = 317, ChairNumber = 2, TheaterRowId = 22 },
                        new { Id = 318, ChairNumber = 3, TheaterRowId = 22 },
                        new { Id = 319, ChairNumber = 4, TheaterRowId = 22 },
                        new { Id = 320, ChairNumber = 5, TheaterRowId = 22 },
                        new { Id = 321, ChairNumber = 6, TheaterRowId = 22 },
                        new { Id = 322, ChairNumber = 7, TheaterRowId = 22 },
                        new { Id = 323, ChairNumber = 8, TheaterRowId = 22 },
                        new { Id = 324, ChairNumber = 9, TheaterRowId = 22 },
                        new { Id = 325, ChairNumber = 10, TheaterRowId = 22 },
                        new { Id = 326, ChairNumber = 11, TheaterRowId = 22 },
                        new { Id = 327, ChairNumber = 12, TheaterRowId = 22 },
                        new { Id = 328, ChairNumber = 13, TheaterRowId = 22 },
                        new { Id = 329, ChairNumber = 14, TheaterRowId = 22 },
                        new { Id = 330, ChairNumber = 15, TheaterRowId = 22 },
                        new { Id = 331, ChairNumber = 1, TheaterRowId = 23 },
                        new { Id = 332, ChairNumber = 2, TheaterRowId = 23 },
                        new { Id = 333, ChairNumber = 3, TheaterRowId = 23 },
                        new { Id = 334, ChairNumber = 4, TheaterRowId = 23 },
                        new { Id = 335, ChairNumber = 5, TheaterRowId = 23 },
                        new { Id = 336, ChairNumber = 6, TheaterRowId = 23 },
                        new { Id = 337, ChairNumber = 7, TheaterRowId = 23 },
                        new { Id = 338, ChairNumber = 8, TheaterRowId = 23 },
                        new { Id = 339, ChairNumber = 9, TheaterRowId = 23 },
                        new { Id = 340, ChairNumber = 10, TheaterRowId = 23 },
                        new { Id = 341, ChairNumber = 11, TheaterRowId = 23 },
                        new { Id = 342, ChairNumber = 12, TheaterRowId = 23 },
                        new { Id = 343, ChairNumber = 13, TheaterRowId = 23 },
                        new { Id = 344, ChairNumber = 14, TheaterRowId = 23 },
                        new { Id = 345, ChairNumber = 15, TheaterRowId = 23 },
                        new { Id = 346, ChairNumber = 1, TheaterRowId = 24 },
                        new { Id = 347, ChairNumber = 2, TheaterRowId = 24 },
                        new { Id = 348, ChairNumber = 3, TheaterRowId = 24 },
                        new { Id = 349, ChairNumber = 4, TheaterRowId = 24 },
                        new { Id = 350, ChairNumber = 5, TheaterRowId = 24 },
                        new { Id = 351, ChairNumber = 6, TheaterRowId = 24 },
                        new { Id = 352, ChairNumber = 7, TheaterRowId = 24 },
                        new { Id = 353, ChairNumber = 8, TheaterRowId = 24 },
                        new { Id = 354, ChairNumber = 9, TheaterRowId = 24 },
                        new { Id = 355, ChairNumber = 10, TheaterRowId = 24 },
                        new { Id = 356, ChairNumber = 11, TheaterRowId = 24 },
                        new { Id = 357, ChairNumber = 12, TheaterRowId = 24 },
                        new { Id = 358, ChairNumber = 13, TheaterRowId = 24 },
                        new { Id = 359, ChairNumber = 14, TheaterRowId = 24 },
                        new { Id = 360, ChairNumber = 15, TheaterRowId = 24 },
                        new { Id = 361, ChairNumber = 1, TheaterRowId = 25 },
                        new { Id = 362, ChairNumber = 2, TheaterRowId = 25 },
                        new { Id = 363, ChairNumber = 3, TheaterRowId = 25 },
                        new { Id = 364, ChairNumber = 4, TheaterRowId = 25 },
                        new { Id = 365, ChairNumber = 5, TheaterRowId = 25 },
                        new { Id = 366, ChairNumber = 6, TheaterRowId = 25 },
                        new { Id = 367, ChairNumber = 7, TheaterRowId = 25 },
                        new { Id = 368, ChairNumber = 8, TheaterRowId = 25 },
                        new { Id = 369, ChairNumber = 9, TheaterRowId = 25 },
                        new { Id = 370, ChairNumber = 10, TheaterRowId = 25 },
                        new { Id = 371, ChairNumber = 1, TheaterRowId = 26 },
                        new { Id = 372, ChairNumber = 2, TheaterRowId = 26 },
                        new { Id = 373, ChairNumber = 3, TheaterRowId = 26 },
                        new { Id = 374, ChairNumber = 4, TheaterRowId = 26 },
                        new { Id = 375, ChairNumber = 5, TheaterRowId = 26 },
                        new { Id = 376, ChairNumber = 6, TheaterRowId = 26 },
                        new { Id = 377, ChairNumber = 7, TheaterRowId = 26 },
                        new { Id = 378, ChairNumber = 8, TheaterRowId = 26 },
                        new { Id = 379, ChairNumber = 9, TheaterRowId = 26 },
                        new { Id = 380, ChairNumber = 10, TheaterRowId = 26 },
                        new { Id = 381, ChairNumber = 1, TheaterRowId = 27 },
                        new { Id = 382, ChairNumber = 2, TheaterRowId = 27 },
                        new { Id = 383, ChairNumber = 3, TheaterRowId = 27 },
                        new { Id = 384, ChairNumber = 4, TheaterRowId = 27 },
                        new { Id = 385, ChairNumber = 5, TheaterRowId = 27 },
                        new { Id = 386, ChairNumber = 6, TheaterRowId = 27 },
                        new { Id = 387, ChairNumber = 7, TheaterRowId = 27 },
                        new { Id = 388, ChairNumber = 8, TheaterRowId = 27 },
                        new { Id = 389, ChairNumber = 9, TheaterRowId = 27 },
                        new { Id = 390, ChairNumber = 10, TheaterRowId = 27 },
                        new { Id = 391, ChairNumber = 1, TheaterRowId = 28 },
                        new { Id = 392, ChairNumber = 2, TheaterRowId = 28 },
                        new { Id = 393, ChairNumber = 3, TheaterRowId = 28 },
                        new { Id = 394, ChairNumber = 4, TheaterRowId = 28 },
                        new { Id = 395, ChairNumber = 5, TheaterRowId = 28 },
                        new { Id = 396, ChairNumber = 6, TheaterRowId = 28 },
                        new { Id = 397, ChairNumber = 7, TheaterRowId = 28 },
                        new { Id = 398, ChairNumber = 8, TheaterRowId = 28 },
                        new { Id = 399, ChairNumber = 9, TheaterRowId = 28 },
                        new { Id = 400, ChairNumber = 10, TheaterRowId = 28 },
                        new { Id = 401, ChairNumber = 1, TheaterRowId = 29 },
                        new { Id = 402, ChairNumber = 2, TheaterRowId = 29 },
                        new { Id = 403, ChairNumber = 3, TheaterRowId = 29 },
                        new { Id = 404, ChairNumber = 4, TheaterRowId = 29 },
                        new { Id = 405, ChairNumber = 5, TheaterRowId = 29 },
                        new { Id = 406, ChairNumber = 6, TheaterRowId = 29 },
                        new { Id = 407, ChairNumber = 7, TheaterRowId = 29 },
                        new { Id = 408, ChairNumber = 8, TheaterRowId = 29 },
                        new { Id = 409, ChairNumber = 9, TheaterRowId = 29 },
                        new { Id = 410, ChairNumber = 10, TheaterRowId = 29 },
                        new { Id = 411, ChairNumber = 1, TheaterRowId = 30 },
                        new { Id = 412, ChairNumber = 2, TheaterRowId = 30 },
                        new { Id = 413, ChairNumber = 3, TheaterRowId = 30 },
                        new { Id = 414, ChairNumber = 4, TheaterRowId = 30 },
                        new { Id = 415, ChairNumber = 5, TheaterRowId = 30 },
                        new { Id = 416, ChairNumber = 6, TheaterRowId = 30 },
                        new { Id = 417, ChairNumber = 7, TheaterRowId = 30 },
                        new { Id = 418, ChairNumber = 8, TheaterRowId = 30 },
                        new { Id = 419, ChairNumber = 9, TheaterRowId = 30 },
                        new { Id = 420, ChairNumber = 10, TheaterRowId = 30 },
                        new { Id = 421, ChairNumber = 1, TheaterRowId = 31 },
                        new { Id = 422, ChairNumber = 2, TheaterRowId = 31 },
                        new { Id = 423, ChairNumber = 3, TheaterRowId = 31 },
                        new { Id = 424, ChairNumber = 4, TheaterRowId = 31 },
                        new { Id = 425, ChairNumber = 5, TheaterRowId = 31 },
                        new { Id = 426, ChairNumber = 6, TheaterRowId = 31 },
                        new { Id = 427, ChairNumber = 7, TheaterRowId = 31 },
                        new { Id = 428, ChairNumber = 8, TheaterRowId = 31 },
                        new { Id = 429, ChairNumber = 9, TheaterRowId = 31 },
                        new { Id = 430, ChairNumber = 10, TheaterRowId = 31 },
                        new { Id = 431, ChairNumber = 1, TheaterRowId = 32 },
                        new { Id = 432, ChairNumber = 2, TheaterRowId = 32 },
                        new { Id = 433, ChairNumber = 3, TheaterRowId = 32 },
                        new { Id = 434, ChairNumber = 4, TheaterRowId = 32 },
                        new { Id = 435, ChairNumber = 5, TheaterRowId = 32 },
                        new { Id = 436, ChairNumber = 6, TheaterRowId = 32 },
                        new { Id = 437, ChairNumber = 7, TheaterRowId = 32 },
                        new { Id = 438, ChairNumber = 8, TheaterRowId = 32 },
                        new { Id = 439, ChairNumber = 9, TheaterRowId = 32 },
                        new { Id = 440, ChairNumber = 10, TheaterRowId = 32 },
                        new { Id = 441, ChairNumber = 1, TheaterRowId = 33 },
                        new { Id = 442, ChairNumber = 2, TheaterRowId = 33 },
                        new { Id = 443, ChairNumber = 3, TheaterRowId = 33 },
                        new { Id = 444, ChairNumber = 4, TheaterRowId = 33 },
                        new { Id = 445, ChairNumber = 5, TheaterRowId = 33 },
                        new { Id = 446, ChairNumber = 6, TheaterRowId = 33 },
                        new { Id = 447, ChairNumber = 7, TheaterRowId = 33 },
                        new { Id = 448, ChairNumber = 8, TheaterRowId = 33 },
                        new { Id = 449, ChairNumber = 9, TheaterRowId = 33 },
                        new { Id = 450, ChairNumber = 10, TheaterRowId = 33 },
                        new { Id = 451, ChairNumber = 11, TheaterRowId = 33 },
                        new { Id = 452, ChairNumber = 12, TheaterRowId = 33 },
                        new { Id = 453, ChairNumber = 13, TheaterRowId = 33 },
                        new { Id = 454, ChairNumber = 14, TheaterRowId = 33 },
                        new { Id = 455, ChairNumber = 15, TheaterRowId = 33 },
                        new { Id = 456, ChairNumber = 1, TheaterRowId = 34 },
                        new { Id = 457, ChairNumber = 2, TheaterRowId = 34 },
                        new { Id = 458, ChairNumber = 3, TheaterRowId = 34 },
                        new { Id = 459, ChairNumber = 4, TheaterRowId = 34 },
                        new { Id = 460, ChairNumber = 5, TheaterRowId = 34 },
                        new { Id = 461, ChairNumber = 6, TheaterRowId = 34 },
                        new { Id = 462, ChairNumber = 7, TheaterRowId = 34 },
                        new { Id = 463, ChairNumber = 8, TheaterRowId = 34 },
                        new { Id = 464, ChairNumber = 9, TheaterRowId = 34 },
                        new { Id = 465, ChairNumber = 10, TheaterRowId = 34 },
                        new { Id = 466, ChairNumber = 11, TheaterRowId = 34 },
                        new { Id = 467, ChairNumber = 12, TheaterRowId = 34 },
                        new { Id = 468, ChairNumber = 13, TheaterRowId = 34 },
                        new { Id = 469, ChairNumber = 14, TheaterRowId = 34 },
                        new { Id = 470, ChairNumber = 15, TheaterRowId = 34 },
                        new { Id = 471, ChairNumber = 1, TheaterRowId = 35 },
                        new { Id = 472, ChairNumber = 2, TheaterRowId = 35 },
                        new { Id = 473, ChairNumber = 3, TheaterRowId = 35 },
                        new { Id = 474, ChairNumber = 4, TheaterRowId = 35 },
                        new { Id = 475, ChairNumber = 5, TheaterRowId = 35 },
                        new { Id = 476, ChairNumber = 6, TheaterRowId = 35 },
                        new { Id = 477, ChairNumber = 7, TheaterRowId = 35 },
                        new { Id = 478, ChairNumber = 8, TheaterRowId = 35 },
                        new { Id = 479, ChairNumber = 9, TheaterRowId = 35 },
                        new { Id = 480, ChairNumber = 10, TheaterRowId = 35 },
                        new { Id = 481, ChairNumber = 1, TheaterRowId = 36 },
                        new { Id = 482, ChairNumber = 2, TheaterRowId = 36 },
                        new { Id = 483, ChairNumber = 3, TheaterRowId = 36 },
                        new { Id = 484, ChairNumber = 4, TheaterRowId = 36 },
                        new { Id = 485, ChairNumber = 5, TheaterRowId = 36 },
                        new { Id = 486, ChairNumber = 6, TheaterRowId = 36 },
                        new { Id = 487, ChairNumber = 7, TheaterRowId = 36 },
                        new { Id = 488, ChairNumber = 8, TheaterRowId = 36 },
                        new { Id = 489, ChairNumber = 9, TheaterRowId = 36 },
                        new { Id = 490, ChairNumber = 10, TheaterRowId = 36 },
                        new { Id = 491, ChairNumber = 1, TheaterRowId = 37 },
                        new { Id = 492, ChairNumber = 2, TheaterRowId = 37 },
                        new { Id = 493, ChairNumber = 3, TheaterRowId = 37 },
                        new { Id = 494, ChairNumber = 4, TheaterRowId = 37 },
                        new { Id = 495, ChairNumber = 5, TheaterRowId = 37 },
                        new { Id = 496, ChairNumber = 6, TheaterRowId = 37 },
                        new { Id = 497, ChairNumber = 7, TheaterRowId = 37 },
                        new { Id = 498, ChairNumber = 8, TheaterRowId = 37 },
                        new { Id = 499, ChairNumber = 9, TheaterRowId = 37 },
                        new { Id = 500, ChairNumber = 10, TheaterRowId = 37 },
                        new { Id = 501, ChairNumber = 11, TheaterRowId = 37 },
                        new { Id = 502, ChairNumber = 12, TheaterRowId = 37 },
                        new { Id = 503, ChairNumber = 13, TheaterRowId = 37 },
                        new { Id = 504, ChairNumber = 14, TheaterRowId = 37 },
                        new { Id = 505, ChairNumber = 15, TheaterRowId = 37 },
                        new { Id = 506, ChairNumber = 1, TheaterRowId = 38 },
                        new { Id = 507, ChairNumber = 2, TheaterRowId = 38 },
                        new { Id = 508, ChairNumber = 3, TheaterRowId = 38 },
                        new { Id = 509, ChairNumber = 4, TheaterRowId = 38 },
                        new { Id = 510, ChairNumber = 5, TheaterRowId = 38 },
                        new { Id = 511, ChairNumber = 6, TheaterRowId = 38 },
                        new { Id = 512, ChairNumber = 7, TheaterRowId = 38 },
                        new { Id = 513, ChairNumber = 8, TheaterRowId = 38 },
                        new { Id = 514, ChairNumber = 9, TheaterRowId = 38 },
                        new { Id = 515, ChairNumber = 10, TheaterRowId = 38 },
                        new { Id = 516, ChairNumber = 11, TheaterRowId = 38 },
                        new { Id = 517, ChairNumber = 12, TheaterRowId = 38 },
                        new { Id = 518, ChairNumber = 13, TheaterRowId = 38 },
                        new { Id = 519, ChairNumber = 14, TheaterRowId = 38 },
                        new { Id = 520, ChairNumber = 15, TheaterRowId = 38 }
                    );
                });

            modelBuilder.Entity("Screend.Entities.Theater.TheaterRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RowName")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<int>("TheaterId");

                    b.HasKey("Id");

                    b.HasIndex("TheaterId");

                    b.ToTable("TheaterRows");

                    b.HasData(
                        new { Id = 1, RowName = "A", TheaterId = 1 },
                        new { Id = 2, RowName = "B", TheaterId = 1 },
                        new { Id = 3, RowName = "C", TheaterId = 1 },
                        new { Id = 4, RowName = "D", TheaterId = 1 },
                        new { Id = 5, RowName = "E", TheaterId = 1 },
                        new { Id = 6, RowName = "F", TheaterId = 1 },
                        new { Id = 7, RowName = "G", TheaterId = 1 },
                        new { Id = 8, RowName = "H", TheaterId = 1 },
                        new { Id = 9, RowName = "A", TheaterId = 2 },
                        new { Id = 10, RowName = "B", TheaterId = 2 },
                        new { Id = 11, RowName = "C", TheaterId = 2 },
                        new { Id = 12, RowName = "D", TheaterId = 2 },
                        new { Id = 13, RowName = "E", TheaterId = 2 },
                        new { Id = 14, RowName = "F", TheaterId = 2 },
                        new { Id = 15, RowName = "G", TheaterId = 2 },
                        new { Id = 16, RowName = "H", TheaterId = 2 },
                        new { Id = 17, RowName = "A", TheaterId = 3 },
                        new { Id = 18, RowName = "B", TheaterId = 3 },
                        new { Id = 19, RowName = "C", TheaterId = 3 },
                        new { Id = 20, RowName = "D", TheaterId = 3 },
                        new { Id = 21, RowName = "E", TheaterId = 3 },
                        new { Id = 22, RowName = "F", TheaterId = 3 },
                        new { Id = 23, RowName = "G", TheaterId = 3 },
                        new { Id = 24, RowName = "H", TheaterId = 3 },
                        new { Id = 25, RowName = "A", TheaterId = 4 },
                        new { Id = 26, RowName = "B", TheaterId = 4 },
                        new { Id = 27, RowName = "C", TheaterId = 4 },
                        new { Id = 28, RowName = "D", TheaterId = 4 },
                        new { Id = 29, RowName = "E", TheaterId = 4 },
                        new { Id = 30, RowName = "F", TheaterId = 4 },
                        new { Id = 31, RowName = "A", TheaterId = 5 },
                        new { Id = 32, RowName = "B", TheaterId = 5 },
                        new { Id = 33, RowName = "C", TheaterId = 5 },
                        new { Id = 34, RowName = "D", TheaterId = 5 },
                        new { Id = 35, RowName = "A", TheaterId = 6 },
                        new { Id = 36, RowName = "B", TheaterId = 6 },
                        new { Id = 37, RowName = "C", TheaterId = 6 },
                        new { Id = 38, RowName = "D", TheaterId = 6 }
                    );
                });

            modelBuilder.Entity("Screend.Entities.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Token");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Screend.Entities.Order.Order", b =>
                {
                    b.HasOne("Screend.Entities.User.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Screend.Entities.Order.OrderArticle", b =>
                {
                    b.HasOne("Screend.Entities.Theater.TheaterArticle", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Screend.Entities.Order.Order", "Order")
                        .WithMany("OrderArticles")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Screend.Entities.Order.OrderChair", b =>
                {
                    b.HasOne("Screend.Entities.Movie.MovieTicket", "MovieTicket")
                        .WithMany()
                        .HasForeignKey("MovieTicketId");

                    b.HasOne("Screend.Entities.Order.Order", "Order")
                        .WithMany("OrderChairs")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Screend.Entities.Schedule.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Screend.Entities.Theater.TheaterChair", "TheaterChair")
                        .WithMany()
                        .HasForeignKey("TheaterChairId");
                });

            modelBuilder.Entity("Screend.Entities.Schedule.Schedule", b =>
                {
                    b.HasOne("Screend.Entities.Movie.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Screend.Entities.Theater.Theater", "Theater")
                        .WithMany("Schedules")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Screend.Entities.Theater.TheaterChair", b =>
                {
                    b.HasOne("Screend.Entities.Theater.TheaterRow", "TheaterRow")
                        .WithMany("TheaterChairs")
                        .HasForeignKey("TheaterRowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Screend.Entities.Theater.TheaterRow", b =>
                {
                    b.HasOne("Screend.Entities.Theater.Theater", "Theater")
                        .WithMany("Rows")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
